version: '3.8'

services:
  backend:
    build:
      context: ./PreqinAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    networks:
      - app-network

  frontend:
    build:
      context: ./preqin-frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./preqin-frontend/build:/usr/share/nginx/html  
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
